### ISSUE TITLE
gradle helmDeploy explanation

### ISSUE THREAD

**Issue by wind57** [kiwigrid/helm-gradle-plugin#13]
Well, before I issue a PR (if that will be needed at all), I have a question. 

How do I configure the plugin so that `gradle helmDeploy` works? In case I am missing the obvious here... thank you

**Comment by jekkel** [comment]
you'd have to use the `deployTo` property of the `helm` extension. See [readme](https://github.com/kiwigrid/helm-gradle-plugin#configure) at the very bottom. It expects one of the configured repositories as argument. Within each repository you can define how to deploy there by invoking `deployVia` mini-DSL, for example like this:
```
helm {
    repositories {
        myRepo {
            url "https://my.repo"
            deployVia 'PUT' to 'https://example.de/' 
            // also supports 'POST'; filename will be appended if url ends with '/' and method is 'PUT'
            // shortcut if url is the same as:
            // deployVia 'PUT' toFetchUrl()
        }
    }
    deployTo repositories.myRepo
}
```

**Comment by wind57** [comment]
right, I saw that. but when I try to run `gradle helmDeploy`, I get:

```
Some problems were found with the configuration of task ':helmDeploy' (type 'HelmDeployTask').
> No value has been specified for property 'chartFolder'.
> No value has been specified for property 'target'.
```

and I look at the code it kind of make sense? those properties are not configured anywhere... thus my initial question actually. Is this a bug that needs to be fixed?

**Comment by wind57** [comment]
It surely looks like this is a tiny bug, I'll work on a fix and test it out against one of our end-points...

**Comment by jekkel** [comment]
Oh, that might be the case indeed as it's not tested regularly (did I mention we need some tests?). As written in the readme I actually discourage the built-in deploy feature as there's no real standard for deploying to chart repositories and usually dedicated tooling does a better job. For example one can use the artifactory Jenkins plugin to push charts to an artifactory hosted repository while recording build meta-data the artifact will be annotated with.

Still I'm looking forward to your PR :+1:
