### ISSUE TITLE
document supported tasks + add a few samples

### ISSUE THREAD

**Issue by wind57** [kiwigrid/helm-gradle-plugin#8]
I know it's always easy to just find out the tasks from `gradle` itself, but it would be so much nicer if these were mentioned in the documentation. Also, some minor samples would be really good too. We have people on our team that are not that versatile with gradle and they had a small-ish hard time understanding this plugin and its usage.

**Comment by kiwi-oss** [comment]
Maybe you have missed the readme file? The tasks are [listed and explained there](https://github.com/kiwigrid/helm-gradle-plugin/blob/master/README.md#what) and there is a [usage example](https://github.com/kiwigrid/helm-gradle-plugin/blob/master/README.md#usage)

**Comment by wind57** [comment]
you are probably right. I was more thinking on the side of explicitly stating some things like : "to package the helm chart, just use `gradle XXX`"... I'll think about it and I guess close this. This was a complaint from one of my colleagues.
